apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers: 
    - name: client
      image: douglira/multi-webapp:latest
      ports:
        - containerPort: 3000
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"